const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');

const API_URL = 'http://localhost:3000/api/message';
const REPORT_FILE = 'EVALUATION_REPORT.md';

const testCases = [
    { question: "What time is check-in?", expectedKeywords: ["3:00 PM", "check-in"], category: "Hotel Policy" },
    { question: "Do you have free wifi?", expectedKeywords: ["Wi-Fi", "HotelGuest"], category: "Amenities" },
    { question: "Can I bring my dog?", expectedKeywords: ["pets", "cleaning fee"], category: "Hotel Policy" },
    { question: "Where can I eat nearby?", expectedKeywords: ["restaurant", "dining"], category: "Local Recommendations" },
    { question: "I need a taxi to the airport", expectedKeywords: ["taxi", "shuttle"], category: "Transportation" },
    { question: "Is breakfast included?", expectedKeywords: ["Breakfast", "7:00"], category: "Dining" },
    { question: "Do you have a gym?", expectedKeywords: ["gym", "2nd floor"], category: "Amenities" },
    { question: "Can you store my bags?", expectedKeywords: ["luggage", "storage"], category: "Services" },
    { question: "How do I get to the city center?", expectedKeywords: ["taxi", "transport"], category: "Transportation" },
    { question: "Hello", expectedKeywords: ["Hello", "Welcome", "help"], category: "Greeting" }
];

async function runTests() {
    console.log('🚀 Starting Bot Evaluation...');
    console.log(`Target: ${API_URL}\n`);

    let passed = 0;
    let results = [];

    for (const test of testCases) {
        process.stdout.write(`Testing: "${test.question}"... `);

        try {
            const start = Date.now();
            const res = await fetch(API_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    sessionId: 'test-eval-bot',
                    message: test.question,
                    conversationHistory: []
                })
            });

            if (!res.ok) {
                throw new Error(`HTTP ${res.status}`);
            }

            const data = await res.json();
            const duration = Date.now() - start;
            const reply = data.reply || "";

            const isMatch = test.expectedKeywords.some(kw => reply.toLowerCase().includes(kw.toLowerCase()));

            if (isMatch) {
                passed++;
                console.log('✅ PASS');
            } else {
                console.log('❌ FAIL');
            }

            results.push({
                ...test,
                actualReply: reply,
                passed: isMatch,
                duration
            });

        } catch (err) {
            console.log('⚠️ ERROR');
            results.push({
                ...test,
                actualReply: `Error: ${err.message}`,
                passed: false,
                duration: 0
            });
        }
    }

    const accuracy = (passed / testCases.length) * 100;
    console.log(`\n📊 Evaluation Complete!`);
    console.log(`Accuracy: ${accuracy}% (${passed}/${testCases.length})`);

    generateReport(results, accuracy);
}

function generateReport(results, accuracy) {
    const report = `
# 📊 Bot Evaluation Report
**Date:** ${new Date().toLocaleString()}
**Overall Accuracy:** ${accuracy}%

## Summary
| Category | Total | Passed | Failed |
|----------|-------|--------|--------|
${Object.entries(results.reduce((acc, r) => {
        acc[r.category] = acc[r.category] || { total: 0, passed: 0 };
        acc[r.category].total++;
        if (r.passed) acc[r.category].passed++;
        return acc;
    }, {})).map(([cat, stats]) => `| ${cat} | ${stats.total} | ${stats.passed} | ${stats.total - stats.passed} |`).join('\n')}

## Detailed Results

| Status | Question | Expected Keywords | Actual Reply | Latency |
|--------|----------|-------------------|--------------|---------|
${results.map(r => `| ${r.passed ? '✅' : '❌'} | ${r.question} | ${r.expectedKeywords.join(', ')} | ${r.actualReply.replace(/\n/g, ' ').substring(0, 50)}... | ${r.duration}ms |`).join('\n')}

## Methodology
This report was generated by sending a set of ${results.length} test queries to the running bot instance and verifying if the response contained expected keywords. This measures the **Retrieval Accuracy** (for RAG) and **Intent Recognition** (for general queries).
`;

    fs.writeFileSync(REPORT_FILE, report);
    console.log(`\n📝 Report saved to ${REPORT_FILE}`);
}

runTests();
